name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of ATAuth is affected?
      options:
        - Rust Library
        - TypeScript Library
        - Gateway Server
        - Documentation
        - CI/CD
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this behavior?
      placeholder: |
        1. Configure...
        2. Call...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide relevant environment information
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 14]
        - Rust version: [e.g., 1.75.0]
        - Node.js version: [e.g., 20.10.0]
        - ATAuth version: [e.g., 1.0.0]

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: If applicable, add logs or error messages.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation
          required: true
