name: Security Report
description: Report a security vulnerability (for non-critical issues)
title: "[Security]: "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a security issue. For critical vulnerabilities, please email the maintainers directly instead of opening a public issue.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this security issue?
      options:
        - Low - Minor issue with limited impact
        - Medium - Moderate impact, workaround available
        - High - Significant impact, no easy workaround
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of ATAuth is affected?
      options:
        - Rust Library
        - TypeScript Library
        - Gateway Server
        - Dependencies
        - CI/CD
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security issue. Be specific but avoid including exploit code.
      placeholder: The issue is...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker do by exploiting this vulnerability?
      placeholder: An attacker could...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we verify this vulnerability exists?
      placeholder: |
        1. Configure...
        2. Send request...
        3. Observe...

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have ideas for how to fix this, please share them.
      placeholder: This could be fixed by...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have verified this is not a critical vulnerability that should be reported privately
          required: true
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
