{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atauth-gateway.fullname" . }}-secrets
  labels:
    {{- include "atauth-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.adminToken }}
  ADMIN_TOKEN: {{ .Values.secrets.adminToken | quote }}
  {{- end }}
  {{- if .Values.secrets.oidcKeySecret }}
  OIDC_KEY_SECRET: {{ .Values.secrets.oidcKeySecret | quote }}
  {{- end }}
  {{- if .Values.secrets.mfaEncryptionKey }}
  MFA_ENCRYPTION_KEY: {{ .Values.secrets.mfaEncryptionKey | quote }}
  {{- end }}
  {{- if and .Values.config.email.enabled .Values.secrets.smtp.host }}
  SMTP_HOST: {{ .Values.secrets.smtp.host | quote }}
  SMTP_PORT: {{ .Values.secrets.smtp.port | quote }}
  SMTP_SECURE: {{ .Values.secrets.smtp.secure | quote }}
  SMTP_USER: {{ .Values.secrets.smtp.user | quote }}
  SMTP_PASS: {{ .Values.secrets.smtp.pass | quote }}
  {{- end }}
  {{- if .Values.secrets.emailApiKey }}
  EMAIL_API_KEY: {{ .Values.secrets.emailApiKey | quote }}
  {{- end }}
{{- end }}
