---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: atauth-gateway-trigger-template
  namespace: tekton-pipelines
spec:
  params:
    - name: git-revision
      description: The git revision
      default: main
    - name: git-url
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: atauth-gateway-build-
      spec:
        pipelineRef:
          name: atauth-gateway-build
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: image-tag
            value: $(tt.params.git-revision)
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: docker-credentials
            secret:
              secretName: registry-credentials
        podTemplate:
          securityContext:
            fsGroup: 65532
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: atauth-gateway-trigger-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: git-revision
      value: $(body.ref)
    - name: git-url
      value: $(body.repository.clone_url)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: atauth-gateway-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: gitea-push
      interceptors:
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.ref in ['refs/heads/main', 'refs/heads/develop']"
            - name: "overlays"
              value:
                - key: truncated_sha
                  expression: "body.after.truncate(7)"
      bindings:
        - ref: atauth-gateway-trigger-binding
      template:
        ref: atauth-gateway-trigger-template
---
apiVersion: v1
kind: Service
metadata:
  name: el-atauth-gateway-listener
  namespace: tekton-pipelines
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    eventlistener: atauth-gateway-listener
