apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atauth-gateway-staging-tailscale
  namespace: atauth-staging
  labels:
    app.kubernetes.io/name: atauth-gateway
    app.kubernetes.io/component: ingress
    environment: staging
  annotations: {}
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: atauth-gateway-staging
      port:
        number: 80
  tls:
    - hosts:
        - auth-staging
